"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, AlertCircle, CheckCircle2, Clock3, RefreshCcw, Search } from "lucide-react";
import { apiFetch } from "@/lib/api";
import { GovPageHeader } from "@/components/layout/GovPageHeader";

export interface LiveColumn { label:string; keys:string[] }
interface Props { title:string; description:string; eyebrow:string; endpoint:string; emptyMessage:string; columns:LiveColumn[]; primaryAction?:{label:string;href:string} }
const read=(record:any,keys:string[])=>{for(const key of keys){const value=key.split(".").reduce((item,part)=>item?.[part],record);if(value!==undefined&&value!==null&&value!=="")return typeof value==="object"?JSON.stringify(value):String(value).replace(/_/g," ")}return "—"};
const statusTone=(status:string)=>/APPROV|ACTIVE|COMPLETE|RESOLVED/i.test(status)?"border-emerald-200 bg-emerald-50 text-emerald-700":/REJECT|OVERDUE|ESCALAT|FAILED/i.test(status)?"border-rose-200 bg-rose-50 text-rose-700":/PENDING|AWAIT|CLARIF|SUBMIT/i.test(status)?"border-amber-200 bg-amber-50 text-amber-800":"border-blue-200 bg-blue-50 text-blue-700";

export default function LiveOperationalPage({title,description,eyebrow,endpoint,emptyMessage,columns,primaryAction}:Props){
  const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [search,setSearch]=useState("");const [asOf,setAsOf]=useState<Date|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response:any=await apiFetch(endpoint);const payload=response?.data??response;const list=Array.isArray(payload)?payload:Object.values(payload||{}).find(Array.isArray)||[];setItems(list as any[]);setAsOf(new Date())}catch(e:any){setError(e?.message||"Live data could not be loaded")}finally{setLoading(false)}},[endpoint]);
  useEffect(()=>{load()},[load]);
  const filtered=useMemo(()=>items.filter(item=>JSON.stringify(item).toLowerCase().includes(search.toLowerCase())),[items,search]);
  const statuses=useMemo(()=>{const result:Record<string,number>={};items.forEach(item=>{const key=String(item.status||item.currentStatus||"RECORDED").replace(/_/g," ");result[key]=(result[key]||0)+1});return result},[items]);
  const summaryCards=[{label:"Total visible",value:items.length,tone:"blue"},...Object.entries(statuses).slice(0,3).map(([label,value],index)=>({label,value,tone:["emerald","amber","indigo"][index]}))];
  return <div className="min-h-screen bg-[#f5f6f8] px-4 py-7 text-[#14274e] md:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6"><GovPageHeader title={title} description={description} eyebrow={eyebrow}/>
    <div className="flex flex-wrap items-center justify-between gap-3"><span className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-[10px] font-semibold text-slate-500 shadow-2xs"><Clock3 size={12}/>{asOf?`Live as of ${asOf.toLocaleString()}`:"Loading authoritative data"}</span>{primaryAction&&<Link href={primaryAction.href} className="rounded-xl bg-[#14274e] px-4 py-2.5 text-xs font-bold text-white shadow-sm transition hover:bg-blue-950 hover:no-underline">{primaryAction.label}</Link>}</div>
    {error?<div role="alert" className="rounded-xl border border-red-200 bg-gradient-to-r from-red-50 to-white p-5 shadow-sm"><div className="flex gap-3"><div className="h-fit rounded-lg border border-red-200 bg-white p-2 text-red-600"><AlertCircle size={18}/></div><div><h2 className="text-sm font-extrabold text-red-950">Data unavailable</h2><p className="mt-1 text-xs font-medium text-red-700">{error}. No sample records are shown.</p><button onClick={load} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-red-700 px-3.5 py-2 text-xs font-bold text-white"><RefreshCcw size={13}/>Retry</button></div></div></div>:<>
      <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{summaryCards.map((card,index)=><div key={card.label} className="group relative h-[105px] overflow-hidden rounded-xl border border-slate-200/90 bg-gradient-to-br from-white via-slate-50/70 to-blue-50/30 p-3.5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><div className={`absolute inset-x-0 top-0 h-1 ${index===0?"bg-gradient-to-r from-blue-500 to-indigo-600":index===1?"bg-gradient-to-r from-emerald-500 to-teal-600":index===2?"bg-gradient-to-r from-amber-500 to-orange-600":"bg-gradient-to-r from-indigo-500 to-purple-600"}`}/><div className="flex items-center justify-between pt-0.5"><span className="truncate pr-2 text-[11px] font-bold uppercase tracking-wide text-slate-600">{card.label}</span><span className="rounded-lg border border-blue-100 bg-blue-50 p-1.5 text-blue-700">{index===0?<Activity size={14}/>:<CheckCircle2 size={14}/>}</span></div><p className="mt-2 font-heading text-2xl font-black text-[#14274e]">{card.value}</p></div>)}</section>
      <section className="overflow-hidden rounded-xl border border-slate-200/80 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 bg-gradient-to-r from-white to-slate-50/70 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-extrabold text-[#14274e]">Live records</h2><p className="mt-0.5 text-[10px] font-medium uppercase tracking-wide text-slate-400">Role and organization scoped</p></div><div className="relative w-full sm:max-w-sm"><Search className="absolute left-3 top-2.5 text-slate-400" size={15}/><input aria-label={`Search ${title}`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search or filter records…" className="w-full rounded-xl border border-slate-200 bg-white py-2 pl-9 pr-3 text-xs font-medium text-slate-800 shadow-2xs outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-500/10"/></div></div>
        {loading?<div className="space-y-3 p-5 animate-pulse">{Array.from({length:5}).map((_,index)=><div key={index} className="h-11 rounded-lg bg-slate-100"/>)}</div>:filtered.length===0?<div className="p-14 text-center"><CheckCircle2 className="mx-auto text-emerald-600"/><p className="mt-3 text-sm font-bold text-slate-800">{emptyMessage}</p><p className="mt-1 text-xs text-slate-500">This is a valid zero state based on live portal data.</p></div>:<div className="overflow-x-auto"><table className="w-full text-left"><thead className="border-b border-slate-200 bg-[#f8fafc] text-[10px] font-extrabold uppercase tracking-wider text-slate-500"><tr>{columns.map(column=><th key={column.label} className="whitespace-nowrap px-5 py-3">{column.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item,index)=><tr key={item.id||index} className="transition hover:bg-blue-50/30">{columns.map((column,columnIndex)=>{const value=read(item,column.keys);return <td key={column.label} className="max-w-sm px-5 py-3 text-xs font-medium text-slate-600">{column.label.toLowerCase().includes("status")?<span className={`inline-flex rounded-md border px-2 py-1 text-[9px] font-extrabold uppercase ${statusTone(value)}`}>{value}</span>:columnIndex===0?<span className="font-bold text-[#14274e]">{value}</span>:value}</td>})}</tr>)}</tbody></table></div>}
      </section></>}
  </div></div>;
}
