"use client";
import { useEffect, useState } from "react";
import { AlertCircle, CheckCircle2, Loader2, RefreshCcw } from "lucide-react";
import GovPortalLayout from "@/components/layout/GovPortalLayout";
import { GovPageHeader } from "@/components/layout/GovPageHeader";
import { apiFetch } from "@/lib/api";
import { useAuthStore } from "@/store/authStore";

export default function GovernmentAssignmentPage(){
  const user=useAuthStore(s=>s.user); const roles=useAuthStore(s=>s.roles); const roleText=[...(roles||[]),user?.role||""].join(" ").toUpperCase(); const isJs=roleText.includes("JOINT_SECRETARY")||Number(user?.roleNumericId||user?.roleId)===3;
  const [data,setData]=useState<any>({pendingCases:[],assignments:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState(""); const [options,setOptions]=useState<Record<string,any>>({}); const [selection,setSelection]=useState<Record<string,{organizationId:string;nodalId:string}>>({});
  const load=()=>{setLoading(true);setError("");apiFetch<any>("/government-assignments").then(r=>setData(r?.data||{pendingCases:[],assignments:[]})).catch(e=>setError(e.message)).finally(()=>setLoading(false))}; useEffect(load,[]);
  const loadOptions=async(caseId:string)=>{setBusy(caseId);try{const r:any=await apiFetch(`/government-assignments/options/${caseId}`);setOptions(x=>({...x,[caseId]:r?.data||{}}))}catch(e:any){setError(e.message)}finally{setBusy("")}};
  const assign=async(caseRecord:any)=>{const picked=selection[caseRecord.id];if(!picked?.organizationId||!picked?.nodalId)return setError("Select the owning CSR Cell and its active Nodal Officer.");setBusy(caseRecord.id);setError("");try{await apiFetch("/government-assignments",{method:"POST",body:JSON.stringify({caseId:caseRecord.id,governmentOrganizationId:picked.organizationId,primaryNodalUserId:picked.nodalId,districtAssignments:(caseRecord.targetDistricts||[]).map((district:string)=>({district}))})});load()}catch(e:any){setError(e.message)}finally{setBusy("")}};
  const act=async(id:string,action:"ACCEPT"|"REJECT"|"ESCALATE")=>{const reason=action==="ACCEPT"?"":window.prompt(action==="REJECT"?"Enter mandatory rejection reason:":"Explain why the district assignment is incorrect:")||"";if(action!=="ACCEPT"&&!reason.trim())return;setBusy(id);try{await apiFetch(`/government-assignments/${id}/${action==="ESCALATE"?"escalate-wrong-district":"respond"}`,{method:"POST",body:JSON.stringify(action==="ESCALATE"?{reason}:{decision:action,reason})});load()}catch(e:any){setError(e.message)}finally{setBusy("")}};
  const reassign=async(item:any)=>{const candidates=item.governmentOrganization?.memberships?.map((m:any)=>m.user)||[];const summary=candidates.map((u:any)=>`${u.id}: ${u.firstName} ${u.lastName||""}`).join("\n");const replacementNodalUserId=window.prompt(`Enter replacement Nodal user ID:\n${summary}`)||"";if(!replacementNodalUserId)return;setBusy(item.id);try{await apiFetch(`/government-assignments/${item.id}/reassign-nodal`,{method:"POST",body:JSON.stringify({replacementNodalUserId,reason:"Reassigned by CSR Cell Head after rejection"})});load()}catch(e:any){setError(e.message)}finally{setBusy("")}};
  return <GovPortalLayout><main className="mx-auto min-h-screen max-w-6xl px-4 py-6"><GovPageHeader title="Government Assignment Workspace" eyebrow="Controlled ownership handoff" description="Single-district cases route to an active main District CSR Cell. Multi-district cases remain State CSR Cell owned with district execution records and a complete audit history."/>{error&&<div role="alert" className="mt-5 flex gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-800"><AlertCircle size={17}/>{error}<button onClick={load} className="ml-auto"><RefreshCcw size={16}/></button></div>}
  {loading?<div className="flex justify-center py-24"><Loader2 className="animate-spin"/></div>:<div className="mt-6 space-y-7">{isJs&&<section><h2 className="font-black text-slate-950">Cases awaiting government owner</h2><p className="mt-1 text-sm text-slate-500">{data.pendingCases.length} JS-approved case(s) need an authoritative owner.</p><div className="mt-3 space-y-3">{data.pendingCases.length===0?<Empty text="No approved cases are awaiting assignment."/>:data.pendingCases.map((item:any)=>{const opt=options[item.id];const chosenOrg=opt?.organizations?.find((o:any)=>o.id===selection[item.id]?.organizationId);return <article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold text-blue-800">{item.trackingId} · {item.geographicScope?.replace(/_/g," ")}</p><h3 className="mt-1 font-bold">{item.title||item.type}</h3><p className="text-xs text-slate-500">Districts: {(item.targetDistricts||[]).join(", ")}</p></div>{!opt?<button disabled={busy===item.id} onClick={()=>loadOptions(item.id)} className="h-fit rounded-lg bg-blue-950 px-4 py-2 text-xs font-bold text-white">Load eligible CSR Cells</button>:<span className="h-fit rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-800">{opt.ownershipLevel} OWNER</span>}</div>{opt&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><select className="rounded-xl border p-3 text-sm" value={selection[item.id]?.organizationId||""} onChange={e=>setSelection(s=>({...s,[item.id]:{organizationId:e.target.value,nodalId:""}}))}><option value="">Select eligible CSR Cell</option>{opt.organizations.map((o:any)=><option key={o.id} value={o.id}>{o.name}{o.district?` — ${o.district}`:""}</option>)}</select><select className="rounded-xl border p-3 text-sm" value={selection[item.id]?.nodalId||""} onChange={e=>setSelection(s=>({...s,[item.id]:{...(s[item.id]||{organizationId:""}),nodalId:e.target.value}}))}><option value="">Select active Nodal Officer</option>{chosenOrg?.memberships?.map((m:any)=><option key={m.user.id} value={m.user.id}>{m.user.firstName} {m.user.lastName||""} — {m.user.designation||"Nodal Officer"}</option>)}</select><button disabled={busy===item.id} onClick={()=>assign(item)} className="rounded-xl bg-emerald-800 px-4 py-3 text-sm font-bold text-white sm:col-span-2">Issue assignment & send for Nodal acceptance</button></div>}</article>})}</div></section>}
  <section><h2 className="font-black text-slate-950">Role-scoped assignment register</h2><p className="mt-1 text-sm text-slate-500">Only records within your operational or oversight scope appear here.</p><div className="mt-3 space-y-3">{data.assignments.length===0?<Empty text="No government assignments are visible in your scope."/>:data.assignments.map((item:any)=>{const mine=item.primaryNodalUserId===user?.id;const isHead=item.governmentOrganization?.departmentHeadUserId===user?.id||item.csrCellHeadUserId===user?.id;return <article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold text-blue-800">{item.case?.trackingId} · {item.ownershipLevel} OWNERSHIP</p><h3 className="mt-1 font-bold">{item.case?.title||item.case?.type}</h3><p className="mt-1 text-xs text-slate-500">{item.governmentOrganization?.name||"Awaiting district owner"} · {(item.case?.targetDistricts||[]).join(", ")}</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{item.status.replace(/_/g," ")}</span></div><div className="mt-4 flex flex-wrap justify-end gap-2">{mine&&item.status==="PENDING_ACCEPTANCE"&&<><button disabled={busy===item.id} onClick={()=>act(item.id,"REJECT")} className="rounded-lg border border-rose-300 px-3 py-2 text-xs font-bold text-rose-800">Reject with reason</button><button disabled={busy===item.id} onClick={()=>act(item.id,"ACCEPT")} className="rounded-lg bg-emerald-800 px-3 py-2 text-xs font-bold text-white">Accept assignment</button></>}{(mine||isHead)&&!["COMPLETED","CLOSED","REVOKED"].includes(item.status)&&<button disabled={busy===item.id} onClick={()=>act(item.id,"ESCALATE")} className="rounded-lg border border-amber-300 px-3 py-2 text-xs font-bold text-amber-900">Wrong district escalation</button>}{isHead&&item.status==="REJECTED_AWAITING_HEAD_REASSIGNMENT"&&<button disabled={busy===item.id} onClick={()=>reassign(item)} className="rounded-lg bg-blue-950 px-3 py-2 text-xs font-bold text-white">Reassign Nodal</button>}</div></article>})}</div></section></div>}</main></GovPortalLayout>
}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center"><CheckCircle2 className="mx-auto text-emerald-700"/><p className="mt-2 text-sm font-semibold text-slate-600">{text}</p></div>}
