import { NextFunction, Request, Response } from "express";
import bcrypt from "bcryptjs";
import crypto from "crypto";
import prisma from "../config/db";
import { AuthenticatedRequest } from "../middlewares/authMiddleware";
import { OtpSendLimitError, sendOtp, verifyOtp } from "../services/otpService";
import { sendUserInvitationEmail } from "../services/emailService";

const MAIN_DESIGNATIONS: Record<string, string> = {
  COLLECTORATE: "Collector",
  ZILLA_PARISHAD: "Chief Executive Officer, Zilla Parishad",
  MUNICIPAL_CORPORATION: "Municipal Commissioner",
};

function temporaryPassword() {
  return `Mha!${crypto.randomBytes(8).toString("base64url")}9a`;
}

function normalizeEmail(value: unknown) {
  return String(value || "").trim().toLowerCase();
}

function normalizeMobile(value: unknown) {
  return String(value || "").replace(/[\s-]/g, "").trim() || null;
}

function isValidMobile(value: string | null) {
  return value === null || /^\+?[1-9]\d{9,14}$/.test(value);
}

function isUniqueConstraintError(error: unknown, field: string) {
  const candidate = error as { code?: string; meta?: { target?: unknown } };
  const targets = Array.isArray(candidate?.meta?.target) ? candidate.meta.target.map(String) : [String(candidate?.meta?.target || "")];
  return candidate?.code === "P2002" && targets.includes(field);
}

function isTransactionTimeoutError(error: unknown) {
  const candidate = error as { code?: string; message?: string; meta?: { error?: string } };
  const detail = `${candidate?.message || ""} ${candidate?.meta?.error || ""}`;
  return candidate?.code === "P2028" && /transaction already closed|expired transaction|timeout/i.test(detail);
}

function fullNameParts(value: unknown) {
  const parts = String(value || "").trim().split(/\s+/).filter(Boolean);
  return { firstName: parts.shift() || "Officer", lastName: parts.join(" ") || null };
}

async function mailTemporaryCredentials(email: string, name: string, roleName: string, password: string) {
  await sendUserInvitationEmail({
    to: email,
    applicantName: name,
    roleName,
    password,
    loginUrl: "/login",
    isAutogenerated: true,
  }).catch((error) => console.error("Government onboarding credential email failed", { email, error: error?.message }));
}

export const requestGovernmentOnboardingOtp = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const email = normalizeEmail(req.body.headEmail);
    const existing = await prisma.user.findFirst({ where: { email }, select: { id: true } });
    if (existing) return res.status(409).json({ success: false, error: "An account already exists for this organization Head email. Sign in or use a different official email." });
    const result = await sendOtp("GOVERNMENT_ONBOARDING", "EMAIL", email);
    return res.json({ success: true, message: "OTP sent to the organization Head's official email", ...result });
  } catch (error) {
    if (error instanceof OtpSendLimitError) return res.status(429).json({ success: false, error: { code: "OTP_RATE_LIMITED", message: error.message }, retryAfterSeconds: error.retryAfterSeconds, sendsRemaining: error.sendsRemaining });
    next(error);
  }
};

export const registerMainGovernmentOrganization = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { governmentType, organizationName, district, address, head, nodal, otp } = req.body;
    const headEmail = normalizeEmail(head?.email);
    const headMobile = normalizeMobile(head?.mobile);
    const nodalEmail = nodal?.email ? normalizeEmail(nodal.email) : null;
    const nodalMobile = nodal?.mobile ? normalizeMobile(nodal.mobile) : null;

    if (!MAIN_DESIGNATIONS[governmentType]) return res.status(400).json({ error: "Only Collectorate, Zilla Parishad, or Municipal Corporation may register as a main organization" });
    if (!headEmail) return res.status(400).json({ error: "Organization Head email is required" });
    if (nodalEmail && headEmail === nodalEmail) return res.status(400).json({ error: "Head and Nodal Officer must have separate official email identities" });
    if (!isValidMobile(headMobile) || (nodalMobile && !isValidMobile(nodalMobile))) return res.status(400).json({ error: "Enter a valid mobile number with 10 to 15 digits, or leave the optional mobile field blank." });
    if (headMobile && nodalMobile && headMobile === nodalMobile) return res.status(400).json({ error: "Head and Nodal Officer must use separate mobile numbers, or leave one optional mobile field blank." });

    const checkEmails = [headEmail, ...(nodalEmail ? [nodalEmail] : [])];
    const mobiles = [headMobile, ...(nodalMobile ? [nodalMobile] : [])].filter((value): value is string => Boolean(value));
    const existing = await prisma.user.findFirst({
      where: { OR: [{ email: { in: checkEmails } }, ...(mobiles.length ? [{ mobile: { in: mobiles } }] : [])] },
      select: { email: true, mobile: true },
    });
    if (existing?.email && checkEmails.includes(existing.email)) return res.status(409).json({ error: `An account already exists for ${existing.email}. Sign in or use a different official email.` });
    if (existing?.mobile) return res.status(409).json({ error: "One of these mobile numbers is already linked to a portal account. Use a different official mobile number or leave the optional field blank." });

    // Enforce at most 1 active/pending main organization for each of Collectorate, Zilla Parishad, Municipal Corporation per district
    const normalizedDistrict = String(district || "").trim();
    const existingMainOrg = await prisma.organization.findFirst({
      where: {
        governmentType,
        governmentLevel: "MAIN",
        district: { equals: normalizedDistrict, mode: "insensitive" },
        status: { in: ["ACTIVE", "UNDER_VERIFICATION", "PROFILE_INCOMPLETE", "CLARIFICATION_REQUIRED"] },
        deletedAt: null,
      },
      select: { id: true, name: true, status: true },
    });
    if (existingMainOrg) {
      return res.status(409).json({
        error: `A main ${governmentType.replace("_", " ")} already exists in ${normalizedDistrict} district (${existingMainOrg.name}). Only one active organization of this type is permitted per district.`
      });
    }

    // Verify only after all correctable conflicts have been checked so a failed registration does not consume the OTP.
    await verifyOtp("GOVERNMENT_ONBOARDING", "EMAIL", headEmail, String(otp), { allowVerifiedReplay: true });

    const headPassword = temporaryPassword();
    const nodalPassword = nodalEmail ? temporaryPassword() : null;
    const expiry = new Date(Date.now() + 72 * 60 * 60 * 1000);
    const headName = fullNameParts(head.name);
    const nodalName = nodal?.name ? fullNameParts(nodal.name) : null;
    
    const headPasswordHash = await bcrypt.hash(headPassword, 12);
    const nodalPasswordHash = nodalPassword ? await bcrypt.hash(nodalPassword, 12) : null;

    let result;
    try {
      result = await prisma.$transaction(async (tx) => {
        const organization = await tx.organization.create({ data: {
          kind: "GOVERNMENT_DEPARTMENT",
          name: String(organizationName).trim(),
          governmentType,
          governmentLevel: "MAIN",
          organizationCode: `GOV-${crypto.randomBytes(4).toString("hex").toUpperCase()}`,
          district: String(district).trim(),
          address: String(address || "").trim() || null,
          officialEmail: headEmail,
          status: "PROFILE_INCOMPLETE",
        }});
        const headUser = await tx.user.create({ data: {
          email: headEmail, loginIdentifier: headEmail, passwordHash: headPasswordHash,
          firstName: headName.firstName, lastName: headName.lastName, mobile: headMobile,
          designation: MAIN_DESIGNATIONS[governmentType], roleId: 7, organizationId: organization.id,
          accountStatus: "ACTIVE", isVerified: true, mustResetPassword: true, temporaryPasswordExpiresAt: expiry,
        }});
        
        let nodalUser = null;
        if (nodalEmail && nodalName && nodalPasswordHash) {
          nodalUser = await tx.user.create({ data: {
            email: nodalEmail, loginIdentifier: nodalEmail, passwordHash: nodalPasswordHash,
            firstName: nodalName.firstName, lastName: nodalName.lastName, mobile: nodalMobile,
            designation: nodal?.designation || "Designated Nodal Officer", roleId: 7, organizationId: organization.id,
            accountStatus: "ACTIVE", isVerified: true, mustResetPassword: true, temporaryPasswordExpiresAt: expiry,
          }});
        }

        await tx.organization.update({ 
          where: { id: organization.id }, 
          data: { 
            departmentHeadUserId: headUser.id, 
            operationalNodalUserId: nodalUser ? nodalUser.id : null 
          } 
        });

        await tx.organizationMembership.create({
          data: { organizationId: organization.id, userId: headUser.id, roleId: 7, membershipType: "HEAD", status: "PENDING_FIRST_LOGIN" }
        });
        
        if (nodalUser) {
          await tx.organizationMembership.create({
            data: { organizationId: organization.id, userId: nodalUser.id, roleId: 7, membershipType: "NODAL", status: "PENDING_FIRST_LOGIN" }
          });
        }

        const application = await tx.governmentOnboardingApplication.create({ data: {
          organizationId: organization.id, organizationLevel: "MAIN", reviewerRoleCode: "JOINT_SECRETARY",
          formData: req.body, status: "DRAFT",
        }});
        await tx.auditLog.create({ data: { action: "GOVERNMENT_MAIN_REGISTERED", entityType: "Organization", entityId: organization.id, details: { governmentType, district, headUserId: headUser.id, nodalUserId: nodalUser ? nodalUser.id : null } } });
        return { organization, application, headUser, nodalUser };
      }, { maxWait: 10_000, timeout: 20_000 });
    } catch (error) {
      if (isUniqueConstraintError(error, "mobile")) return res.status(409).json({ error: "One of these mobile numbers was just linked to another portal account. Use a different official mobile number or leave the optional field blank." });
      if (isUniqueConstraintError(error, "email") || isUniqueConstraintError(error, "loginIdentifier")) return res.status(409).json({ error: "One of these official emails was just registered. Sign in or use a different official email." });
      if (isTransactionTimeoutError(error)) return res.status(503).json({ error: "The database took too long to complete registration. Your OTP is still valid; please press Verify again." });
      throw error;
    }

    const mailPromises = [
      mailTemporaryCredentials(headEmail, String(head.name), MAIN_DESIGNATIONS[governmentType], headPassword)
    ];
    if (result.nodalUser && nodalEmail && nodalPassword && nodal?.name) {
      mailPromises.push(mailTemporaryCredentials(nodalEmail, String(nodal.name), "Designated Nodal Officer", nodalPassword));
    }
    await Promise.all(mailPromises);
    return res.status(201).json({ success: true, organizationId: result.organization.id, applicationId: result.application.id, status: result.application.status, message: "Organization registered. Head of the organization must reset their temporary password before first login." });
  } catch (error) { next(error); }
};

export const submitGovernmentOnboarding = async (req: AuthenticatedRequest, res: Response, next: NextFunction) => {
  try {
    const organizationId = req.params.organizationId;
    const membership = await prisma.organizationMembership.findFirst({ where: { organizationId, userId: req.user!.id, membershipType: { in: ["HEAD", "ADMIN"] }, status: "ACTIVE" } });
    if (!membership) return res.status(403).json({ error: "Only the active organization Head/Admin can submit onboarding" });
    const current = await prisma.governmentOnboardingApplication.findFirst({ where: { organizationId }, orderBy: { version: "desc" } });
    if (!current || !["DRAFT", "CLARIFICATION_REQUIRED"].includes(current.status)) return res.status(409).json({ error: "No editable onboarding application is available" });
    const application = await prisma.$transaction(async (tx) => {
      const updated = current.status === "CLARIFICATION_REQUIRED"
        ? await tx.governmentOnboardingApplication.create({ data: { organizationId, organizationLevel: current.organizationLevel, reviewerRoleCode: current.reviewerRoleCode, version: current.version + 1, formData: req.body.formData || current.formData, documentSnapshot: req.body.documents || current.documentSnapshot || undefined, status: "UNDER_VERIFICATION", submittedByUserId: req.user!.id, submittedAt: new Date() } })
        : await tx.governmentOnboardingApplication.update({ where: { id: current.id }, data: { formData: req.body.formData || current.formData, documentSnapshot: req.body.documents || undefined, status: "UNDER_VERIFICATION", submittedByUserId: req.user!.id, submittedAt: new Date(), decision: null, decisionRemarks: null } });
      await tx.organization.update({ where: { id: organizationId }, data: { status: "UNDER_VERIFICATION", clarificationRemarks: null } });
      await tx.auditLog.create({ data: { actorUserId: req.user!.id, userId: req.user!.id, action: "GOVERNMENT_ONBOARDING_SUBMITTED", entityType: "GovernmentOnboardingApplication", entityId: updated.id, details: { version: updated.version, previousVersionId: current.status === "CLARIFICATION_REQUIRED" ? current.id : null, reviewerRoleCode: current.reviewerRoleCode } } });
      return updated;
    });
    return res.json({ success: true, application });
  } catch (error) { next(error); }
};

export const createSubDepartment = async (req: AuthenticatedRequest, res: Response, next: NextFunction) => {
  try {
    const parentId = req.params.organizationId;
    const parent = await prisma.organization.findFirst({ where: { id: parentId, governmentLevel: "MAIN", status: "ACTIVE" } });
    if (!parent) return res.status(409).json({ error: "Sub-departments can only be created under an active main organization" });
    const actor = await prisma.organizationMembership.findFirst({ where: { organizationId: parentId, userId: req.user!.id, membershipType: { in: ["HEAD", "NODAL", "ADMIN"] }, status: "ACTIVE" } });
    if (!actor) return res.status(403).json({ error: "You do not administer this organization" });
    const { name, code, address, admin, nodal } = req.body;
    const duplicate = await prisma.organization.findFirst({ where: { parentOrganizationId: parentId, governmentLevel: "SUB_DEPARTMENT", deletedAt: null, OR: [{ name: { equals: String(name).trim(), mode: "insensitive" } }, ...(code ? [{ organizationCode: { equals: String(code).trim(), mode: "insensitive" as const } }] : [])] } });
    if (duplicate) return res.status(409).json({ error: "A sub-department with the same name or office code already exists under this main organization" });
    const adminEmail = normalizeEmail(admin.email);
    const nodalEmail = nodal?.email ? normalizeEmail(nodal.email) : null;
    if (nodalEmail && adminEmail === nodalEmail) return res.status(400).json({ error: "Sub-department Admin and Nodal Officer require separate identities" });
    const checkEmails = [adminEmail, ...(nodalEmail ? [nodalEmail] : [])];
    if (await prisma.user.findFirst({ where: { email: { in: checkEmails } } })) return res.status(409).json({ error: "One of the supplied officer emails already has an account" });
    const adminPassword = temporaryPassword();
    const nodalPassword = nodalEmail ? temporaryPassword() : null;
    const expiry = new Date(Date.now() + 72 * 60 * 60 * 1000);
    const adminName = fullNameParts(admin.name);
    const adminMobile = admin.mobile || admin.phone || null;
    const nodalName = nodal?.name ? fullNameParts(nodal.name) : null;
    const nodalMobile = nodal?.mobile || nodal?.phone || null;
    const result = await prisma.$transaction(async tx => {
      const organization = await tx.organization.create({ data: { kind: "GOVERNMENT_DEPARTMENT", name, governmentType: "SUB_DEPARTMENT", governmentLevel: "SUB_DEPARTMENT", parentOrganizationId: parentId, organizationCode: code || `SUB-${crypto.randomBytes(4).toString("hex").toUpperCase()}`, address: address || null, district: parent.district, status: "PROFILE_INCOMPLETE", officialEmail: adminEmail } });
      const adminUser = await tx.user.create({ data: { email: adminEmail, loginIdentifier: adminEmail, passwordHash: await bcrypt.hash(adminPassword, 12), firstName: adminName.firstName, lastName: adminName.lastName, designation: admin.designation || "Sub-department Administrator", mobile: adminMobile, roleId: 7, organizationId: organization.id, accountStatus: "ACTIVE", isVerified: true, mustResetPassword: true, temporaryPasswordExpiresAt: expiry } });
      let nodalUser: any = null;
      if (nodalEmail && nodalName && nodalPassword) {
        nodalUser = await tx.user.create({ data: { email: nodalEmail, loginIdentifier: nodalEmail, passwordHash: await bcrypt.hash(nodalPassword, 12), firstName: nodalName.firstName, lastName: nodalName.lastName, designation: nodal?.designation || "Designated Nodal Officer", mobile: nodalMobile, roleId: 7, organizationId: organization.id, accountStatus: "ACTIVE", isVerified: true, mustResetPassword: true, temporaryPasswordExpiresAt: expiry } });
      }
      await tx.organization.update({ where: { id: organization.id }, data: { departmentHeadUserId: adminUser.id, ...(nodalUser ? { operationalNodalUserId: nodalUser.id } : {}) } });
      const membershipsData: any[] = [{ organizationId: organization.id, userId: adminUser.id, roleId: 7, membershipType: "ADMIN", status: "PENDING_FIRST_LOGIN", invitedByUserId: req.user!.id }];
      if (nodalUser) {
        membershipsData.push({ organizationId: organization.id, userId: nodalUser.id, roleId: 7, membershipType: "NODAL", status: "PENDING_FIRST_LOGIN", invitedByUserId: req.user!.id });
      }
      await tx.organizationMembership.createMany({ data: membershipsData });
      const application = await tx.governmentOnboardingApplication.create({ data: { organizationId: organization.id, organizationLevel: "SUB_DEPARTMENT", reviewerRoleCode: "JOINT_SECRETARY", formData: req.body, status: "DRAFT" } });
      await tx.auditLog.create({ data: { actorUserId: req.user!.id, userId: req.user!.id, action: "GOVERNMENT_SUBDEPARTMENT_CREATED", entityType: "Organization", entityId: organization.id, details: { parentId, adminUserId: adminUser.id, nodalUserId: nodalUser?.id || null } } });
      return { organization, application };
    });
    const mailQueue: Promise<any>[] = [mailTemporaryCredentials(adminEmail, admin.name, "Sub-department Administrator", adminPassword)];
    if (nodalEmail && nodalPassword && nodal?.name) {
      mailQueue.push(mailTemporaryCredentials(nodalEmail, nodal.name, "Designated Nodal Officer", nodalPassword));
    }
    await Promise.all(mailQueue);
    return res.status(201).json({ success: true, organizationId: result.organization.id, applicationId: result.application.id });
  } catch (error) { next(error); }
};

export const listOnboardingReviews = async (req: AuthenticatedRequest, res: Response, next: NextFunction) => {
  try {
    const userRole = String(req.user?.role || "").toUpperCase();
    const roleId = Number(req.user?.roleId);

    const isSuperAdmin = roleId === 1 || userRole === "SUPER_ADMIN";
    const isJointSecretary = roleId === 3 || userRole === "JOINT_SECRETARY";
    const isPlanningSecretary = roleId === 2 || userRole === "PLANNING_SECRETARY";

    if (!isSuperAdmin && !isJointSecretary && !isPlanningSecretary) {
      return res.status(403).json({ error: "Reviewer role required" });
    }

    // Joint Secretary / SuperAdmin evaluates ALL applications; Planning Secretary evaluates sub-departments
    const reviewerFilter = (isSuperAdmin || isJointSecretary)
      ? {}
      : { reviewerRoleCode: "PLANNING_SECRETARY" };

    const applications = await prisma.governmentOnboardingApplication.findMany({
      where: {
        ...reviewerFilter,
        status: { in: ["UNDER_VERIFICATION", "CLARIFICATION_REQUIRED"] }
      },
      include: { organization: true },
      orderBy: { submittedAt: "asc" }
    });

    return res.json({
      data: applications,
      counts: {
        awaitingDecision: applications.filter(a => a.status === "UNDER_VERIFICATION").length,
        clarificationRequired: applications.filter(a => a.status === "CLARIFICATION_REQUIRED").length
      }
    });
  } catch (error) { next(error); }
};

export const decideGovernmentOnboarding = async (req: AuthenticatedRequest, res: Response, next: NextFunction) => {
  try {
    const { decision, remarks } = req.body;
    const userRole = String(req.user?.role || "").toUpperCase();
    const roleId = Number(req.user?.roleId);

    const isSuperAdmin = roleId === 1 || userRole === "SUPER_ADMIN";
    const isJointSecretary = roleId === 3 || userRole === "JOINT_SECRETARY";
    const isPlanningSecretary = roleId === 2 || userRole === "PLANNING_SECRETARY";

    if (!isSuperAdmin && !isJointSecretary && !isPlanningSecretary) {
      return res.status(403).json({ error: "You are not authorized to make onboarding decisions" });
    }

    const application = await prisma.governmentOnboardingApplication.findUnique({
      where: { id: req.params.applicationId },
      include: { organization: true }
    });

    if (!application) return res.status(404).json({ error: "Application not found" });

    // Planning Secretary cannot review Joint Secretary main cell applications
    if (isPlanningSecretary && !isJointSecretary && !isSuperAdmin && application.reviewerRoleCode === "JOINT_SECRETARY") {
      return res.status(403).json({ error: "Planning Secretary cannot review Joint Secretary main cell applications" });
    }

    if (application.status !== "UNDER_VERIFICATION") {
      return res.status(409).json({ error: "Application is not awaiting a decision" });
    }

    if (decision !== "APPROVE" && !String(remarks || "").trim()) {
      return res.status(400).json({ error: "Remarks are required for clarification or rejection" });
    }

    const status = decision === "APPROVE" ? "APPROVED" : decision === "CLARIFICATION" ? "CLARIFICATION_REQUIRED" : "REJECTED";
    const organizationStatus = decision === "APPROVE" ? "ACTIVE" : decision === "CLARIFICATION" ? "CLARIFICATION_REQUIRED" : "REJECTED";

    const updated = await prisma.$transaction(async tx => {
      const record = await tx.governmentOnboardingApplication.update({
        where: { id: application.id },
        data: {
          status,
          decision,
          decisionRemarks: remarks || null,
          reviewedByUserId: req.user!.id,
          decidedAt: new Date()
        }
      });
      await tx.organization.update({
        where: { id: application.organizationId },
        data: {
          status: organizationStatus,
          clarificationRemarks: decision === "CLARIFICATION" ? remarks : null,
          rejectionReason: decision === "REJECT" ? remarks : null
        }
      });
      await tx.auditLog.create({
        data: {
          actorUserId: req.user!.id,
          userId: req.user!.id,
          action: `GOVERNMENT_ONBOARDING_${decision}`,
          entityType: "GovernmentOnboardingApplication",
          entityId: application.id,
          details: { remarks: remarks || null, reviewerRoleCode: application.reviewerRoleCode }
        }
      });
      return record;
    });

    return res.json({ success: true, application: updated, organizationStatus });
  } catch (error) { next(error); }
};
