export const TENANT_FEATURES = [
  "enableNGORegistration",
  "enableCompanyRegistration",
  "enableGovernmentDepartmentRegistration",
  "enableRequirementCreation",
  "enableCSRMarketplace",
  "enableCompanyInterest",
  "enableNGOSelection",
  "enableFundDisbursement",
  "enableMilestoneMonitoring",
  "enableGISReports",
  "enableAIReports",
  "enablePublicTransparency",
  "enableReportsExport",
  "enablePaymentModule",
  "enableMessagingModule",
  "enableNotifications",
  "enableDocumentVerification"
] as const;

export const PERMISSIONS = [
  ["requirement:create", "Create department CSR requirements", "requirements"],
  ["requirement:view", "View CSR requirements", "requirements"],
  ["requirement:update", "Update CSR requirements", "requirements"],
  ["requirement:submit", "Submit requirements for approval", "requirements"],
  ["requirement:approve", "Approve requirements", "requirements"],
  ["requirement:publish", "Publish requirements", "requirements"],
  ["requirement:delete", "Delete requirements", "requirements"],
  ["marketplace:view", "View CSR marketplace", "marketplace"],
  ["interest:create", "Create company interest", "interests"],
  ["interest:view", "View company interests", "interests"],
  ["interest:approve", "Approve company interests", "interests"],
  ["project:view", "View CSR projects", "projects"],
  ["project:create", "Create CSR projects", "projects"],
  ["project:update", "Update CSR projects", "projects"],
  ["project:approve", "Approve CSR projects", "projects"],
  ["milestone:create", "Create milestones", "milestones"],
  ["milestone:update", "Update milestones", "milestones"],
  ["milestone:verify", "Verify milestones", "milestones"],
  ["fund:view", "View funds", "funds"],
  ["fund:commit", "Commit funds", "funds"],
  ["fund:release", "Release funds", "funds"],
  ["fund:verify-utilization", "Verify fund utilization", "funds"],
  ["report:view", "View reports", "reports"],
  ["report:export", "Export reports", "reports"],
  ["organization:view", "View organizations", "organization"],
  ["organization:update", "Update organizations", "organization"],
  ["organization:approve", "Approve organizations", "organization"],
  ["organization:suspend", "Suspend organizations", "organization"],
  ["user:invite", "Invite organization users", "users"],
  ["user:update", "Update organization users", "users"],
  ["role:create", "Create roles", "roles"],
  ["role:update", "Update roles", "roles"],
  ["role:delete", "Delete roles", "roles"],
  ["feature-toggle:view", "View feature toggles", "features"],
  ["feature-toggle:update", "Update feature toggles", "features"],
  ["tenant:create", "Create tenants", "tenants"],
  ["tenant:update", "Update tenants", "tenants"],
  ["tenant:disable", "Disable tenants", "tenants"],
  ["tenant:delete", "Delete tenants", "tenants"],
  ["audit:view", "View audit logs", "audit"]
] as const;

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  PORTAL_ADMIN: [
    "organization:view",
    "organization:approve",
    "organization:suspend",
    "requirement:view",
    "requirement:approve",
    "requirement:publish",
    "interest:view",
    "interest:approve",
    "project:view",
    "project:approve",
    "fund:view",
    "fund:verify-utilization",
    "report:view",
    "report:export",
    "audit:view",
    "enquiry:view",
    "enquiry:assign",
    "enquiry:contact"
  ],
  CSR_ADMIN: [
    "organization:view",
    "organization:approve",
    "organization:suspend",
    "requirement:view",
    "requirement:approve",
    "requirement:publish",
    "interest:view",
    "interest:approve",
    "project:view",
    "project:create",
    "project:approve",
    "fund:view",
    "fund:release",
    "fund:verify-utilization",
    "milestone:verify",
    "report:view",
    "report:export",
    "audit:view",
    "enquiry:view",
    "enquiry:assign",
    "enquiry:contact"
  ],
  DISTRICT_ADMIN: ["requirement:view", "requirement:approve", "project:view", "milestone:verify", "report:view", "organization:view"],
  FINANCE_USER: ["fund:view", "fund:release", "fund:verify-utilization", "report:view"],
  ORGANIZATION_VERIFIER: ["organization:view", "organization:approve", "organization:suspend", "audit:view"],
  REQUIREMENT_APPROVER: ["requirement:view", "requirement:approve", "requirement:publish"],
  REPORT_MANAGER: ["report:view", "report:export"],
  FINANCE_REVIEWER: ["fund:view", "fund:release", "fund:verify-utilization"],
  SUPPORT_OFFICER: ["organization:view", "requirement:view", "interest:view", "project:view"],
  DEPARTMENT_ADMIN: [
    "organization:view",
    "organization:update",
    "user:invite",
    "user:update",
    "role:create",
    "role:update",
    "role:delete",
    "requirement:create",
    "requirement:view",
    "requirement:update",
    "requirement:submit",
    "interest:view",
    "project:view",
    "report:view"
  ],
  BENEFICIARY_AGENCY: [
    "organization:view",
    "organization:update",
    "user:invite",
    "user:update",
    "role:create",
    "role:update",
    "role:delete",
    "requirement:create",
    "requirement:view",
    "requirement:update",
    "requirement:submit",
    "interest:view",
    "project:view",
    "project:update",
    "report:view"
  ],
  REQUIREMENT_CREATOR: ["requirement:create", "requirement:view", "requirement:update", "requirement:submit"],
  HANDOVER_OFFICER: ["project:view", "project:update"],
  COMPANY_ADMIN: [
    "organization:view",
    "organization:update",
    "user:invite",
    "user:update",
    "role:create",
    "role:update",
    "role:delete",
    "marketplace:view",
    "interest:create",
    "interest:view",
    "fund:view",
    "fund:commit",
    "report:view"
  ],
  COMPANY_MEMBER: ["marketplace:view", "interest:create", "interest:view", "project:view", "fund:view", "report:view"],
  CSR_HEAD: ["marketplace:view", "interest:create", "interest:view", "project:view", "fund:commit", "report:view"],
  CSR_FINANCE_OFFICER: ["fund:view", "fund:commit", "fund:release", "report:view"],
  CSR_PROJECT_MANAGER: ["project:view", "project:update", "milestone:update", "report:view"],
  NGO_ADMIN: [
    "organization:view",
    "organization:update",
    "user:invite",
    "user:update",
    "role:create",
    "role:update",
    "role:delete",
    "marketplace:view",
    "project:create",
    "project:view",
    "milestone:update",
    "fund:view",
    "report:view"
  ],
  NGO_MEMBER: ["marketplace:view", "project:create", "project:view", "milestone:update", "fund:view", "fund:verify-utilization", "report:view"],
  NGO_PROJECT_COORDINATOR: ["marketplace:view", "project:view", "milestone:update", "report:view"],
  NGO_FINANCE_MANAGER: ["fund:view", "fund:verify-utilization", "report:view"],
  NGO_FIELD_OFFICER: ["project:view", "milestone:update"],
  VIEWER: ["organization:view", "requirement:view", "marketplace:view", "project:view", "report:view"],
  CSR_RELATIONSHIP_MANAGER: ["enquiry:view", "enquiry:contact", "enquiry:assign"],
  JOINT_SECRETARY: ["enquiry:view", "enquiry:assign"],
  STATE_CSR_CELL: ["enquiry:view", "enquiry:assign"],
  PLANNING_SECRETARY: ["enquiry:view"]
};
