export const TENANT_FEATURES = [
  "enableNGORegistration",
  "enableCompanyRegistration",
  "enableGovernmentDepartmentRegistration",
  "enableRequirementCreation",
  "enableCSRMarketplace",
  "enableCompanyInterest",
  "enableNGOSelection",
  "enableFundDisbursement",
  "enableMilestoneMonitoring",
  "enableGISReports",
  "enableAIReports",
  "enablePublicTransparency",
  "enableReportsExport",
  "enablePaymentModule",
  "enableMessagingModule",
  "enableNotifications",
  "enableDocumentVerification"
] as const;

export const PERMISSIONS = [
  ["requirement:create", "Create department CSR requirements", "requirements"],
  ["requirement:view", "View CSR requirements", "requirements"],
  ["requirement:update", "Update CSR requirements", "requirements"],
  ["requirement:submit", "Submit requirements for approval", "requirements"],
  ["requirement:approve", "Approve requirements", "requirements"],
  ["requirement:publish", "Publish requirements", "requirements"],
  ["requirement:delete", "Delete requirements", "requirements"],
  ["marketplace:view", "View CSR marketplace", "marketplace"],
  ["interest:create", "Create company interest", "interests"],
  ["interest:view", "View company interests", "interests"],
  ["interest:approve", "Approve company interests", "interests"],
  ["project:view", "View CSR projects", "projects"],
  ["project:create", "Create CSR projects", "projects"],
  ["project:update", "Update CSR projects", "projects"],
  ["project:approve", "Approve CSR projects", "projects"],
  ["milestone:create", "Create milestones", "milestones"],
  ["milestone:update", "Update milestones", "milestones"],
  ["milestone:verify", "Verify milestones", "milestones"],
  ["fund:view", "View funds", "funds"],
  ["fund:commit", "Commit funds", "funds"],
  ["fund:release", "Release funds", "funds"],
  ["fund:verify-utilization", "Verify fund utilization", "funds"],
  ["report:view", "View reports", "reports"],
  ["report:export", "Export reports", "reports"],
  ["organization:view", "View organizations", "organization"],
  ["organization:update", "Update organizations", "organization"],
  ["organization:approve", "Approve organizations", "organization"],
  ["organization:suspend", "Suspend organizations", "organization"],
  ["user:invite", "Invite organization users", "users"],
  ["user:update", "Update organization users", "users"],
  ["role:create", "Create roles", "roles"],
  ["role:update", "Update roles", "roles"],
  ["role:delete", "Delete roles", "roles"],
  ["role:view", "View roles", "roles"],
  ["role:configure", "Configure roles for users", "roles"],
  ["permission:view", "View permissions", "roles"],
  ["permission:configure", "Configure permissions and groups", "roles"],
  ["feature-toggle:view", "View feature toggles", "features"],
  ["feature-toggle:update", "Update feature toggles", "features"],
  ["tenant:create", "Create tenants", "tenants"],
  ["tenant:update", "Update tenants", "tenants"],
  ["tenant:disable", "Disable tenants", "tenants"],
  ["tenant:delete", "Delete tenants", "tenants"],
  ["audit:view", "View audit logs", "audit"],
  ["enquiry:view", "View corporate enquiries", "enquiries"],
  ["enquiry:assign", "Assign relationship managers to enquiries", "enquiries"],
  ["enquiry:contact", "Record corporate contact interactions", "enquiries"],
  ["project:assign", "Assign officers to approved projects", "assignments"],
  ["officer:create", "Create and invite new officers", "assignments"],
  ["officer:search", "Search existing officers", "assignments"],
  ["role:assignable_list", "List assignable roles for officers", "assignments"],
  ["district_mapping:manage", "Manage district nodal officer mappings", "assignments"],
  ["workflow:view", "View workflow stage and history", "workflow"],
  ["workflow:system_transition", "Perform system workflow transitions", "workflow"]
] as const;

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  SUPER_ADMIN: [
    "organization:view",
    "organization:approve",
    "organization:suspend",
    "requirement:view",
    "requirement:approve",
    "requirement:publish",
    "interest:view",
    "interest:approve",
    "project:view",
    "project:approve",
    "fund:view",
    "fund:release",
    "fund:verify-utilization",
    "milestone:verify",
    "report:view",
    "report:export",
    "audit:view",
    "enquiry:view",
    "enquiry:assign",
    "enquiry:contact",
    "role:view",
    "role:create",
    "role:update",
    "role:delete",
    "role:configure",
    "permission:view",
    "permission:configure",
    "project:assign",
    "officer:create",
    "officer:search",
    "role:assignable_list",
    "district_mapping:manage",
    "workflow:view",
    "workflow:system_transition"
  ],
  CORPORATE_USER: [
    "organization:view",
    "organization:update",
    "user:invite",
    "user:update",
    "role:create",
    "role:update",
    "role:delete",
    "marketplace:view",
    "interest:create",
    "interest:view",
    "fund:view",
    "fund:commit",
    "report:view",
    "project:view"
  ],
  GOVERNMENT_OFFICER: [
    "organization:view",
    "organization:update",
    "user:invite",
    "user:update",
    "role:create",
    "role:update",
    "role:delete",
    "requirement:create",
    "requirement:view",
    "requirement:update",
    "requirement:submit",
    "interest:view",
    "project:view",
    "report:view"
  ],
  "Planning Secretary": [
    "organization:view",
    "organization:approve",
    "organization:suspend",
    "requirement:view",
    "requirement:approve",
    "requirement:publish",
    "interest:view",
    "project:view",
    "project:approve",
    "fund:view",
    "fund:release",
    "fund:verify-utilization",
    "milestone:verify",
    "report:view",
    "report:export",
    "audit:view"
  ],
  "Joint Secretary": [
    "organization:view",
    "organization:approve",
    "requirement:view",
    "requirement:approve",
    "requirement:publish",
    "interest:view",
    "interest:approve",
    "project:view",
    "project:approve",
    "project:assign",
    "officer:search",
    "role:assignable_list",
    "district_mapping:manage",
    "workflow:view",
    "fund:view",
    "fund:release",
    "report:view",
    "report:export"
  ],
  "Relationship Manager": [
    "organization:view",
    "requirement:view",
    "interest:view",
    "project:view",
    "report:view",
    "enquiry:view",
    "enquiry:contact"
  ],
  "District Nodal Officer": [
    "organization:view",
    "requirement:view",
    "project:view",
    "project:update",
    "project:assign",
    "officer:create",
    "officer:search",
    "role:assignable_list",
    "workflow:view",
    "milestone:verify",
    "fund:verify-utilization",
    "report:view"
  ],
  "District Nodal Consultant": [
    "organization:view",
    "requirement:view",
    "project:view",
    "project:update",
    "report:view"
  ],
  "State CSR Cell": [
    "organization:view",
    "requirement:view",
    "project:view",
    "report:view"
  ],
  "NGO Admin": [
    "organization:view",
    "organization:update",
    "user:invite",
    "user:update",
    "role:create",
    "role:update",
    "role:delete",
    "marketplace:view",
    "project:view",
    "project:create",
    "project:update",
    "milestone:create",
    "milestone:update",
    "fund:view",
    "report:view"
  ],
  "Company Admin": [
    "organization:view",
    "organization:update",
    "user:invite",
    "user:update",
    "role:create",
    "role:update",
    "role:delete",
    "marketplace:view",
    "interest:create",
    "interest:view",
    "project:view",
    "fund:view",
    "fund:commit",
    "report:view"
  ],
  "Beneficiary Agency": [
    "organization:view",
    "organization:update",
    "user:invite",
    "user:update",
    "role:create",
    "role:update",
    "role:delete",
    "requirement:create",
    "requirement:view",
    "requirement:update",
    "requirement:submit",
    "project:view",
    "report:view"
  ]
};
